global:                     #全局配置
  namespace: Development     #环境类型, 首字母大写, 正式环境：Production 开发环境：Development 测试环境：Test 根据具体需求可只建立正式环境和开发环境
  env_name: dev          #环境名称, 正式环境: prod  开发环境/测试环境: test
  local_ip: ${POD_IP}               
  container_name: ${HOSTNAME}       


hertz:
  app: "ssg"
  server: "enterbuild"
  enable_pprof: true 
  enable_gzip: true 
  enable_access_log: true  
  service: 
    - name: "HelloService"
      addr: ":8888"

log:                      #日志配置
  log_mode: console
  log_level: debug
  log_file_name: "log/hertz.log"
  log_max_size: 10
  log_max_age: 3
  log_max_backups: 50

registry:                 #注册中心,目前公共库只支持nacos
  name: nacos 
  namespace: "9f36909a-1c02-4ed7-8bc4-d744c6660350"
  registry_address:
    - 10.11.89.99:8848
  username: ""
  password: ""

selector:                 #服务发现,目前公共库只支持nacos
  name: nacos 
  namespace: "9f36909a-1c02-4ed7-8bc4-d744c6660350" 
  server_addr:
    - 10.11.89.99:8848
  username: ""
  password: ""

config:                   #配置中心,目前公共库只支持nacos
  name: nacos 
  namespace: "9f36909a-1c02-4ed7-8bc4-d744c6660350"
  server_addr:
    - 10.11.89.99:8848
  username: ""
  password: ""

prometheus:               #监控配置
  enable: true
  addr: ":9099"
  path: "/prometheus/metrics"